### ISSUE TITLE
Permitir a exportação dos dados da planilha em formato CSV

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-front#11]
# Contexto

Completar.

# Proposta

Completar.

# Definition of Done

Completar.

**Comment by marcelogm** [comment]
@mariemariz pode ser criativa nessa issue.

@hbribeiro77 complementar issue.

**Comment by hbribeiro77** [comment]
Informações que queremos disponibilizar para o usuário:
**Número do processo**,  **Intimado**, **Evento**(identificadorMovimento), **data/hora da expedição da intimação**(dataHoraMovimento), **Descrição**(descricaoMovimento), **Situação**(status), **Prazo,** **Data inicial**(prazoinicioPrazo), **Data final**(finalPrazo), **Órgão julgador**(nomeOrgao), **Código do município**(codigoMunicipioIBGE)

**Comment by zaiosc-dpers** [comment]
@mariemariz Oie, temos alguns ajustes:

- Permitir a exibição correta da acentuação (títulos das colunas e valores);
- Formatar a coluna do processo como texto, pra evitar a visualização padrão do número em notação científica.

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/7ac24fdc-c54e-4a12-b689-faedadcbb910)

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/a8748dc2-02c7-44de-a994-c4d0b94f7beb)


_(atualizando...)_

**Comment by zaiosc-dpers** [comment]
@mariemariz Oi, se puder ser nessa issue, temos esse tratamento da informação em `payload.outros.status` que é feito no Portal, mas que ainda não ocorre no SIE.

XML | Corresponde a: 👇 
|:----|:----|
Aguardando Abertura | Pendente
Aberto | Em curso

OBS.: já foi anotado para ser feito o mesmo tratamento na lista de intimações. https://github.com/DefensoriaPublicaRS/sie-front/issues/13#issuecomment-2111058990

**Comment by zaiosc-dpers** [comment]
Verificado em Produção.

---

Exs.:

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/7af22488-03ab-4d9b-8395-59e32e9c2ec3)

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/124029a2-75fb-4918-808b-e75e8dba6118)


OBS.: As informações sobre o prazo da intimação estão ficando apenas com a data, sendo que a informação completa, normalmente, é de "00:00:00" para a data inicial e de "23:59:59" para a data final, como pode ser percebido no front do SIE. Será indicado na issue (?) para verificar se a modificação é necessária no CSV.
