### ISSUE TITLE
Aplicar verificação de autenticação com middleware

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-front#21]
Isso seria legal ter em todas as requests pro backend. Acho que a request de check hoje não tem.

Será que não conseguimos usar um middleware pra fazer isso?

_Originally posted by @marcelogm in https://github.com/DefensoriaPublicaRS/sie-front/pull/19#discussion_r1598767183_

**Comment by mariemariz** [comment]
Está funcionando nos ambientes de testes e produção. Não funciona localhost pois o arquivo middleware.ts deveria estar na raiz do projeto, coisa que no processo de build deve funcionar.
Foi decido que não precisa fazer nada nesse momento, desse jeito o desenvolvedor consegue acessar localhost sem se logar.
Apenas foi feita uma correção para funcionar a logo da DPE na página de login que estava quebrada assim:

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/3866764/9f7fbe4a-e583-4e1a-be3c-164df945e960)


Com a correção:


![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/3866764/cc97c04c-aef9-4777-9871-d7b46b6a4c2f)
