### ISSUE TITLE
Ao acessar a URL, deve-se manter os parametros da request

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-front#24]
# Contexto

Atualmente se o usuário acessa a aplicação a partir de uma URL com parametros de busca, o frontend faz a busca das intimações de acordo com o filtro, mas as informações nos parametros da URL são perdidos, o que impede a geração do relatório correto.

# Proposta

...

# Definition of Done

Que ao acessar a URL, os parametros se mantenham e o relatório seja gerado de acordo com os parametros.

**Comment by zaiosc-dpers** [comment]
Verificando em Produção...

- Os parâmetros da busca se mantêm:
    - [ ] Ao recarregar a página
    - [ ] Ao acessar o URL (manualmente ou duplicando a aba)
