### ISSUE TITLE
adicionar se a intimação é do Eproc 1G ou 2G  e também a data de disponibilização da intimação no arquivo csv.

### ISSUE THREAD

**Issue by hbribeiro77** [DefensoriaPublicaRS/sie-front#26]
- Adicionar a informação do sistema (se 1G ou 2G à direita da coluna do código do município
- Adicionar a data de disponibilização da intimação após a coluna do sistema de origem.

**Comment by zaiosc-dpers** [comment]
@marcelogm @hbribeiro77 Opa, a posição da coluna "Origem" no CSV não está de acordo com o que consta na descrição da issue. No momento não há uma coluna com a data de disponibilização. 🤔 

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/2e9bc7c7-8269-4567-be63-c50bb1df3e2a)

[intimacoes_51035892120248210001.csv](https://github.com/DefensoriaPublicaRS/sie-front/files/15314611/intimacoes_51035892120248210001.csv)


Por falar na disponibilização, aparentemente o valor de data/hora exibido no front está sendo o que aparece em `createdAt` (na nossa timezone), mas esse não é o momento em que o registro está sendo criado no Mongo? Creio que o mais correto seria usar data/hora de `payload.data`, que é uma informação efetivamente retornada pelo TJ (em tese, quando aquele aviso foi disponibilizado na interop).

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/9a22ea14-02b3-4f8d-b748-243568e1acfd)

&nbsp; | &nbsp;
|:----|:----|
![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/55fc0d2b-3993-47d7-980e-c7adec7ce2bd) | ![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/2cc911db-2cba-4409-bea6-fc8f81a4427d)

**Comment by zaiosc-dpers** [comment]
Após testes realizados em 15/05, verificamos que o valor que está retornando na interoperabilidade para `dataDisponibilizacao` (`payload.data`, no Mongo) é o momento em que a consulta está sendo feita, ou seja, não possui relação com o propósito daquele campo, como pode ser visto no manual de interoperabilidade.

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/1373d504-84ce-4ec6-9848-7188db189a72)

Assim, entramos em contato com o TJ para maiores esclarecimentos.

**Comment by zaiosc-dpers** [comment]
Verificado em https://github.com/DefensoriaPublicaRS/sie-fetcher/issues/10.

---

OBS.: a inclusão da data de importação no CSV será feita em https://github.com/DefensoriaPublicaRS/sie-front/issues/42.
