### ISSUE TITLE
Adicionar no CSV coluna identificando se a intimação é urgente ou não

### ISSUE THREAD

**Issue by hbribeiro77** [DefensoriaPublicaRS/sie-front#41]
No CSV Adicionar coluna informando se é intimação urgente ou não e posicionar essa coluna à direita da coluna com número do processo.

**Comment by zaiosc-dpers** [comment]
Verificando em Testes...

---

_idAviso 202405073022702_

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/5add14d7-adb7-4f12-bd37-bc4cb7cf90f8)

```xml
{
    "_id" : ObjectId("663ba7e01bea17606c5af7a1"),
    "idAviso" : "202405073022702",
    "__v" : NumberInt(0),
    "createdAt" : ISODate("2024-05-08T16:27:12.849+0000"),
    "lastUpdate" : ISODate("2024-05-14T03:10:23.953+0000"),
    "payload" : {
        "id" : "202405073022702",
        "tipo" : "URG",
```

**Comment by zaiosc-dpers** [comment]
Para verificar as não urgentes, depende de https://github.com/DefensoriaPublicaRS/sie-front/issues/23.

OBS.: O teste pode ser feito na issue acima, caso seja desenvolvida.
