### ISSUE TITLE
Habilitar/Desabilitar usuário Administrador

### ISSUE THREAD

**Issue by mariemariz** [DefensoriaPublicaRS/sie-front#46]
# Contexto

Atualmente temos apenas a tela listando usuários, não permitindo sua inclusão, edição ou remoção.

# Proposta

Na página de usuários, para cada usuário listado deve aparecer na coluna Adminsitrador um checkbox ou toggle que, ao ser clicado, deve habilitar/desabilitar o perfil administrador para o usuário. Só poderá realizar essa ação quem tiver uma role específica pra isso (admin).

# Definition of Done

Ter uma maneira de Habilitar/Desabilitar usuário Administrador através da aplicação.

**Comment by zaiosc-dpers** [comment]
No momento tanto o SIE de testes quanto o de produção estão inacessíveis.

Testes| Produção
|:---:|:---:|
![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/d93ada84-150f-4a60-8815-83e1f7827331) | ![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/5a60cd82-75f5-452c-9c2d-b45533aa3b44)

**Comment by zaiosc-dpers** [comment]
Verificando em Produção...

---

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/ecfe9f35-b37f-4715-8981-e82471bd4b15)
