### ISSUE TITLE
Visualizar intimações marcadas como lidas

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-front#5]
# Contexto

Atualmente a aplicação permite que o usuário visualize as intimações urgentes e marque as que foram visualizadas como "Marcar como lida". Após confirmar a ação, o usuário deixa de ver essa intimação permanentemente.

![image](https://github.com/marcelogm/sie-front/assets/13242375/4cf21864-c814-479a-8450-eebbadf8dfb3)

# Proposta

Espera-se que seja possível visualizar as intimações que foram ocultadas a partir do botão de "Marcar como lida".
Também é interessante que seja possível exibir na lista se a intimação já foi visualizada ou não, de modo que fique visualmente claro quais foram visualizadas. Para isso, utilizer um modelo de tag na tabela.

# Definition of Done

Usuário é capaz de filtrar e visualizar claramente intimações marcadas como lidas.

**Comment by DayvitSiqueira** [comment]
Essa tarefa será fechada por solicitação do Humberto, que estabeleceu que a mesma já não será mais necessária.
