### ISSUE TITLE
Publicar aplicação no domínio da defensoria

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-front#51]

**Comment by zaiosc-dpers** [comment]
Verificado em Produção.

---

URL: https://intimacoes.defensoria.rs.def.br


&nbsp; | &nbsp;
|:---:|:---:|
![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/355d7a62-abe4-4c7e-850c-4d469604ce40) | ![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/91277aa4-3e97-4d62-af2c-01975abd5c1f)

![image](https://github.com/DefensoriaPublicaRS/sie-front/assets/169402696/d792eff8-0fc8-4f33-b177-cdb0ffde1ecb)
